name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:

      - name: checkout files
        uses: actions/checkout@v2
      - name: deployment
        uses:  sculpeydev/test-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: "ec2-3-128-123-147.us-east-2.compute.amazonaws.com"
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Deploy Script 1    
        run: mkdir app-express
